steps:
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'python'
    entrypoint: 'pytest'
    args: ['test_app.py']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bmi-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bmi-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'bmi-app',
      '--image', 'gcr.io/$PROJECT_ID/bmi-app',
      '--region', 'australia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
